[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/ffmpeg/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"
